/**
 * Danganronpa RPG - a Remnant wears the icon of the action that left it.
 * ---------------------------------------------------------------------------
 * Dawid, 26.08: every trace on the map shows WHICH action produced it - the
 * Search magnifier, the Sabotage wrench, the murder's own icon - but a player
 * earns that icon by analysing their copy. Until then they see the question
 * mark, the same 8x8 glyph the Despair pool uses.
 *
 * WHY THIS IS A CLIENT-SIDE TEXTURE SWAP AND NOT A DOCUMENT WRITE. The token
 * document travels to every client, so anything written onto it is written to
 * the whole table at once - and "which action left this" is exactly the kind
 * of answer-key fact the Remnant ledger was built to keep off the wire. Worse,
 * the entitlement is PERSONAL: two players looking at the same trace may know
 * different amounts about it, so there is no single texture the document could
 * carry that is right for both. The document therefore always carries the
 * question mark (see `ICON` in remnants.mjs), and each client decides for
 * itself, from what it already legitimately holds, whether to dress the token
 * up:
 *
 *   · a GM reads the action off the ledger - theirs to read;
 *   · a player reads `sourceAction` off their OWN Truth Bullet, a flag that
 *     analyze.mjs publishes onto the item only at identification.
 *
 * The swap is one property assignment on the already-drawn mesh - no DB
 * write, no re-render, nothing for another client to observe. The isometric
 * post-mortem (26.08) is the cautionary tale this file is built against: its
 * refresh path wrote to the database and re-rendered the world 26 times a
 * second. This one only ever assigns a cached texture to a local sprite, and
 * assigning the texture it already has is a no-op.
 */

import { MODULE_ID } from "./config.mjs";
import { REMNANT_FLAGS, remnantData, ICON } from "./remnants.mjs";
import { TRUTH_BULLET_FLAGS, bulletsOf, isIdentified } from "./truth-bullets.mjs";
import { debug, warn } from "./utils.mjs";

/** One file per recorded action - generated by tools/token-icons.mjs. */
const ACTION_ICONS = Object.fromEntries(
    ["search", "project", "sabotage", "dynamic", "resolution", "incident", "discard", "manual"]
        .map(a => [a, `modules/${MODULE_ID}/icons/remnant-${a}.svg`])
);

/** Loaded PIXI textures, by path. Filled once per canvas; misses stay misses. */
const textures = new Map();

/**
 * `remnantRef` → what THIS user's own bullets say about the trace. Rebuilt
 * lazily and dropped on any Truth Bullet change, for the same reason
 * visibility.mjs memoises `myRemnantRefs`: every revealed trace would
 * otherwise re-scan every owned actor's items on every `refreshToken`.
 */
let myBulletFacts = null;

function bulletFacts() {
    if (myBulletFacts) return myBulletFacts;
    const facts = new Map();
    for (const actor of game.actors) {
        if (actor.type !== "character" || !actor.isOwner) continue;
        for (const item of bulletsOf(actor)) {
            const ref = item.getFlag(MODULE_ID, TRUTH_BULLET_FLAGS.remnantRef);
            if (!ref) continue;
            const known = facts.get(ref);
            const action = isIdentified(item)
                ? item.getFlag(MODULE_ID, TRUTH_BULLET_FLAGS.sourceAction) ?? null
                : null;
            // Two owned copies of one trace: whichever knows more wins.
            if (!known?.action) facts.set(ref, { action });
        }
    }
    myBulletFacts = facts;
    return facts;
}

/**
 * Which icon this client has EARNED for one trace, or null for the document's
 * own question mark.
 */
function earnedIcon(tokenDoc) {
    if (game.user.isGM) {
        // The ledger's answer. A trace with no entry (or one recorded before
        // actions were) keeps the question mark rather than guessing.
        return ACTION_ICONS[remnantData(tokenDoc)?.action] ?? null;
    }
    const ref = tokenDoc.parent?.id && tokenDoc.id ? `${tokenDoc.parent.id}.${tokenDoc.id}` : null;
    if (!ref) return null;
    return ACTION_ICONS[bulletFacts().get(ref)?.action] ?? null;
}

/** Dress one token, or undress it back to the document's texture. */
function apply(token) {
    try {
        const doc = token?.document;
        if (!doc?.getFlag?.(MODULE_ID, REMNANT_FLAGS.isRemnant)) return;

        const mesh = token.mesh;
        if (!mesh || mesh.destroyed) return;

        const path = earnedIcon(doc) ?? doc.texture?.src ?? ICON;
        const tex = textures.get(path);
        if (tex && mesh.texture !== tex) mesh.texture = tex;
    } catch (err) {
        debug("Could not dress a Remnant token", err);
    }
}

function applyAll() {
    for (const token of canvas?.tokens?.placeables ?? []) apply(token);
}

/**
 * For remnants.mjs, after a ledger write. A fresh trace is created first and
 * recorded second, so the refresh that drew it ran before there was an action
 * to read - and a settings write refreshes no tokens. Without this nudge the
 * GM's icon waited for the next incidental hover. (Measured in the sandbox:
 * place → question mark until `renderFlags.set` by hand.)
 */
export function repaintRemnants() {
    applyAll();
}

/**
 * Load every icon this client could ever need - the action set for a GM, plus
 * whatever the documents themselves wear - so `apply` stays synchronous on the
 * refresh path. A path that fails to load is dropped and its tokens simply
 * keep the texture Foundry drew; said once out loud, not once per refresh.
 */
async function preload() {
    const load = foundry.canvas.loadTexture ?? globalThis.loadTexture;
    const paths = new Set([ICON, ...Object.values(ACTION_ICONS)]);
    for (const path of paths) {
        if (textures.has(path)) continue;
        try {
            const tex = await load(path);
            if (tex) textures.set(path, tex);
        } catch (err) {
            warn(`Remnant icon did not load: ${path}`, err);
        }
    }
}

/** A Truth Bullet changing hands or state can change what its owner has earned. */
function isBulletChange(item) {
    return item?.parent?.documentName === "Actor"
        && item.getFlag?.(MODULE_ID, "category") === "truthBullet";
}

export function registerRemnantIcons() {
    Hooks.on("canvasReady", () => {
        myBulletFacts = null;
        preload().then(applyAll);
    });

    // After the ring's own refresh handler and Foundry's: refreshToken fires
    // post-refresh, so the mesh this reads is the one on screen.
    Hooks.on("refreshToken", token => apply(token));

    for (const hook of ["createItem", "updateItem", "deleteItem"]) {
        Hooks.on(hook, item => {
            if (!isBulletChange(item)) return;
            myBulletFacts = null;
            applyAll();
        });
    }
}
