/**
 * Danganronpa RPG - a Remnant wears the icon of the action that left it.
 * ---------------------------------------------------------------------------
 * Dawid, 26.08: every trace on the map shows WHICH action produced it - the
 * Search magnifier, the Sabotage wrench, the murder's own icon - but a player
 * earns that icon by analysing their copy. Until then they see the question
 * mark, the same 8x8 glyph the Despair pool uses.
 *
 * WHY THIS IS A CLIENT-SIDE TEXTURE SWAP AND NOT A DOCUMENT WRITE. The token
 * document travels to every client, so anything written onto it is written to
 * the whole table at once - and "which action left this" is exactly the kind
 * of answer-key fact the Remnant ledger was built to keep off the wire. Worse,
 * the entitlement is PERSONAL: two players looking at the same trace may know
 * different amounts about it, so there is no single texture the document could
 * carry that is right for both. The document therefore always carries the
 * question mark (see `ICON` in remnants.mjs), and each client decides for
 * itself, from what it already legitimately holds, whether to dress the token
 * up:
 *
 *   · a GM reads the action off the ledger - theirs to read;
 *   · a player reads `sourceAction` off their OWN Truth Bullet, a flag that
 *     analyze.mjs publishes onto the item only at identification.
 *
 * The swap is one property assignment on the already-drawn mesh - no DB
 * write, no re-render, nothing for another client to observe. The isometric
 * post-mortem (26.08) is the cautionary tale this file is built against: its
 * refresh path wrote to the database and re-rendered the world 26 times a
 * second. This one only ever assigns a cached texture to a local sprite, and
 * assigning the texture it already has is a no-op.
 *
 * AND THE NAME, THE SAME WAY (E05 C13, 27.09.2026; audit S05-39 (1)). Until
 * 1.2.64 a found trace's token took its public name and image as a document
 * write, so a player who had found nothing read another's evidence - what it was
 * called and where it lay - off the token from the console. The token keeps the
 * neutral word and the question mark now (remnants.mjs `propagatePublic`), and
 * this file draws the rest on the screens that may know it (`shownOnTrace`): a
 * GM's from the row's `public`, a finder's from their own bullet - the name the
 * GM gave it when they found it, kept in step by `propagateRemnantPublic`. The
 * nameplate's text and the mesh's texture, on this client alone. Not measured
 * here: the harness has no canvas (LIVE-E05-05).
 */

import { MODULE_ID, itemIcon } from "./config.mjs";
import { REMNANT_FLAGS, remnantData, remnantPublic, keyOf, ICON } from "./remnants.mjs";
import { TRUTH_BULLET_FLAGS, BULLET_CATEGORY, ownBulletRefs, isIdentified } from "./truth-bullets.mjs";
import { debug, warn } from "./utils.mjs";

/** One file per recorded action - generated by tools/token-icons.mjs. */
const ACTION_ICONS = Object.fromEntries(
    ["search", "project", "sabotage", "dynamic", "resolution", "incident", "discard", "manual", "loot"]
        .map(a => [a, `modules/${MODULE_ID}/icons/remnant-${a}.svg`])
);

/** Loaded PIXI textures, by path. Filled once per canvas; misses stay misses. */
const textures = new Map();

/**
 * A trace's key → what THIS user's own bullets say about the trace: the action
 * that left it, once a copy is identified, and the name and image the copy
 * carries. Rebuilt lazily and dropped on any Truth Bullet change and any change
 * of the owner's copy of the keys (E05 C13), for the same reason visibility.mjs
 * memoises `myRemnantRefs`: every revealed trace would otherwise re-scan every
 * owned actor's items on every `refreshToken`.
 */
let myBulletFacts = null;

/** A copy's own picture, or null for the category's placeholder, which shows nothing of the object. */
function ownImage(item) {
    const img = item?.img;
    return img && img !== itemIcon(BULLET_CATEGORY) ? img : null;
}

function bulletFacts() {
    if (myBulletFacts) return myBulletFacts;
    const facts = new Map();
    for (const { item, ref } of ownBulletRefs()) {
        const known = facts.get(ref);
        const action = isIdentified(item)
            ? item.getFlag(MODULE_ID, TRUTH_BULLET_FLAGS.sourceAction) ?? null
            : null;
        // Two owned copies of one trace: whichever knows more wins.
        if (!known?.action) facts.set(ref, { action, name: item.name ?? "", img: ownImage(item) });
    }
    myBulletFacts = facts;
    return facts;
}

/**
 * Which icon this client has EARNED for one trace, or null for the document's
 * own question mark.
 */
function earnedIcon(tokenDoc) {
    if (game.user.isGM) {
        // The ledger's answer. A trace with no entry (or one recorded before
        // actions were) keeps the question mark rather than guessing.
        return ACTION_ICONS[remnantData(tokenDoc)?.action] ?? null;
    }
    const ref = keyOf(tokenDoc);
    if (!ref) return null;
    return ACTION_ICONS[bulletFacts().get(ref)?.action] ?? null;
}

/**
 * What THIS screen calls one trace, `{ name, img }`, or null for the document's
 * own word and question mark (E05 C13): a GM's from the row's `public`, a
 * player's from their own copy of it. Anybody who has not found it draws the
 * document. Exported for the suite and the harness, which have no canvas to
 * read a drawing off.
 */
export function shownOnTrace(tokenDoc) {
    if (!tokenDoc?.getFlag?.(MODULE_ID, REMNANT_FLAGS.isRemnant)) return null;
    if (game.user.isGM) {
        const pub = remnantPublic(tokenDoc);
        return pub ? { name: pub.name || null, img: pub.img || null } : null;
    }
    const ref = keyOf(tokenDoc);
    const fact = ref ? bulletFacts().get(ref) : null;
    return fact ? { name: fact.name || null, img: fact.img } : null;
}

/** Paths being loaded, and paths that would not load - said once each (`textureFor`). */
const loading = new Set();
const missing = new Set();

/**
 * The texture for one path, or null while it is not here. An image a GM chose
 * for one trace is not among the icons `preload` fetches - until E05 C13 it was
 * the document's own texture, which Foundry drew - so it is fetched the first
 * time a screen needs it, and every trace is dressed again once it arrives.
 */
function textureFor(path) {
    const tex = textures.get(path);
    if (tex || !path || loading.has(path) || missing.has(path)) return tex ?? null;
    const load = foundry.canvas?.loadTexture ?? globalThis.loadTexture;
    if (typeof load !== "function") return null;
    loading.add(path);
    Promise.resolve().then(() => load(path))
        .then(loaded => { if (loaded) textures.set(path, loaded); else missing.add(path); })
        .catch(err => { missing.add(path); warn(`A trace's image did not load: ${path}`, err); })
        .finally(() => { loading.delete(path); if (textures.has(path)) applyAll(); });
    return null;
}

/** Dress one token, or undress it back to the document's texture and name. */
function apply(token) {
    try {
        const doc = token?.document;
        if (!doc?.getFlag?.(MODULE_ID, REMNANT_FLAGS.isRemnant)) return;

        const mesh = token.mesh;
        if (!mesh || mesh.destroyed) return;

        const shown = shownOnTrace(doc);
        const path = earnedIcon(doc) ?? shown?.img ?? doc.texture?.src ?? ICON;
        const tex = textureFor(path);
        if (tex && mesh.texture !== tex) mesh.texture = tex;

        // The nameplate Foundry drew from the document's word: this refresh hook
        // runs after every refresh of it, so the name this screen may know stays.
        const plate = token.nameplate;
        const name = shown?.name || doc.name;
        if (plate && !plate.destroyed && plate.text !== name) plate.text = name;
    } catch (err) {
        debug("Could not dress a Remnant token", err);
    }
}

function applyAll() {
    for (const token of canvas?.tokens?.placeables ?? []) apply(token);
}

/**
 * For remnants.mjs, after a ledger write. A fresh trace is created first and
 * recorded second, so the refresh that drew it ran before there was an action
 * to read - and a settings write refreshes no tokens. Without this nudge the
 * GM's icon waited for the next incidental hover. (Measured in the sandbox:
 * place → question mark until `renderFlags.set` by hand.)
 */
export function repaintRemnants() {
    applyAll();
}

/**
 * Load every icon this client could ever need - the action set for a GM, plus
 * whatever the documents themselves wear - so `apply` stays synchronous on the
 * refresh path. A path that fails to load is dropped and its tokens simply
 * keep the texture Foundry drew; said once out loud, not once per refresh.
 */
async function preload() {
    const load = foundry.canvas.loadTexture ?? globalThis.loadTexture;
    const paths = new Set([ICON, ...Object.values(ACTION_ICONS)]);
    for (const path of paths) {
        if (textures.has(path)) continue;
        try {
            const tex = await load(path);
            if (tex) textures.set(path, tex);
        } catch (err) {
            warn(`Remnant icon did not load: ${path}`, err);
        }
    }
}

/** A Truth Bullet changing hands or state can change what its owner has earned. */
function isBulletChange(item) {
    return item?.parent?.documentName === "Actor"
        && item.getFlag?.(MODULE_ID, "category") === "truthBullet";
}

export function registerRemnantIcons() {
    Hooks.on("canvasReady", () => {
        myBulletFacts = null;
        preload().then(applyAll);
    });

    // After the ring's own refresh handler and Foundry's: refreshToken fires
    // post-refresh, so the mesh this reads is the one on screen.
    Hooks.on("refreshToken", token => apply(token));

    for (const hook of ["createItem", "updateItem", "deleteItem"]) {
        Hooks.on(hook, item => {
            if (!isBulletChange(item)) return;
            myBulletFacts = null;
            applyAll();
        });
    }

    // The owner's copy of which trace each bullet came from (E05 C13): it can arrive
    // after the bullet, and it is what the facts above are keyed by.
    Hooks.on("drpgBulletRefsChanged", () => {
        myBulletFacts = null;
        applyAll();
    });
}
